version: '3.3'
services:
  unitask-frontend:
    container_name: unitask-frontend
    image: node:20-alpine
    command: sh -c "npm install && npm run dev"
    working_dir: /var/www/unitask-system
    volumes:
      - .:/var/www/unitask-system
    networks:
      - traefik
    expose:
      - "5173"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unitask-frontend.rule=Host(`unitask.ankocreative.com`)"
      - "traefik.http.routers.unitask-frontend.entrypoints=websecure"
      - "traefik.http.routers.unitask-frontend.tls=true"
      - "traefik.http.routers.unitask-frontend.tls.certresolver=myresolver"
      - "traefik.http.services.unitask-frontend.loadbalancer.server.port=5173"

networks:
  traefik:
    external: true